### ISSUE TITLE
array_multisort purpose

### ISSUE THREAD

**Issue by songofthewings** [ANDREW-LVIV/phplab-tasks#7]
What is the purpose of array_multisort here?
https://github.com/ANDREW-LVIV/phplab-tasks/blob/f75f3c4bb42d33783c381f885c5e4b87d0f86cfc/src/03-arrays.php#L72

**Comment by ANDREW-LVIV** [comment]
I used `array_multisort `for sorting multidimensional arrays. However simple `sort `may also be used as the keys will be sorted anyway! And it will meet requirements.
Do I have to change `array_multisort `to `sort`, because if multidimensional array will containe not only _name_ and _tags_ ut will be nice to have arrays sorted in ascending order?

**Comment by songofthewings** [comment]
There is no sense in using array_multisort - just remove the line, and the logic will be right. This line is just confusing if you leave it. (But if you remove ksort, this array_multisort will not help: it's lexicographical sorting for first argument, you will not have required result in all possible cases (just change values order))

>>if multidimensional array will containe not only name and tags ut will be nice to have arrays sorted in ascending order
- there is no value in sorting $input if it contains other keys. Algorithm complexity stays the same - O(1) to find value by key.

**Comment by ANDREW-LVIV** [comment]
A new logic was implemented to sort multidimensional arrays. Now it should work correctly.
